

spring:
  application:
    name: apigateway

  config:
    import: "optional:configserver:http://localhost:9071"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: read-only

  info:
    env:
      enabled: true

info:
  app:
    name: "API Gateway Server"
    description: "Micro Bank API Gateway Server application"
    version: "1.0.0"