

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect



loan:
  name: loan-service
  version: 1.0.0
  description: Loan Service for managing user loans
  contact:
    name: Kiransing Bhat
    email: bhatkiran74@gmail.com

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

  instance:
    prefer-ip-address: true